import { user } from './user_interface';

export var users_data : user[] = [

    {
        id : 1,
        firstName : 'Larry',
        lastName :  'Hyde',
        age : 31,
        profilePicture : './assets/images/profile_pictures/1.jpg',
        posts : [],
        likedPosts : [],
        stories : [2],
    },
    {
        id : 2,
        firstName : 'James',
        lastName :  'Lambert',
        age : 26,
        profilePicture : './assets/images/profile_pictures/2.jpg',
        posts : [2],
        likedPosts : [],
        stories : [1],
    },
    {
        id : 3,
        firstName : 'Kimberly',
        lastName :  'May',
        age : 21,
        profilePicture : './assets/images/profile_pictures/3.jpg',
        posts : [1],
        likedPosts : [],
        stories : [5],
    },
    {
        id : 4,
        firstName : 'Joshua',
        lastName :  'Schatz',
        age : 19,
        profilePicture : './assets/images/profile_pictures/4.jpg',
        posts : [],
        likedPosts : [],
        stories : [3],
    },
    {
        id : 5,
        firstName : 'John',
        lastName :  'Blauser',
        age : 24,
        profilePicture : './assets/images/profile_pictures/5.jpg',
        posts : [],
        likedPosts : [],
        stories : [4],
    },
    {
        id : 6,
        firstName : 'Lorraine',
        lastName :  'Rainey',
        age : 29,
        profilePicture : './assets/images/profile_pictures/6.jpg',
        posts : [3],
        likedPosts : [],
        stories : [6],
    },

]